# Generated by Django 5.0.4 on 2024-05-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fornone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
