# Generated by Django 5.0.4 on 2024-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookdata', '__first__'),
        ('fornone', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='users', to='bookdata.book'),
        ),
    ]
