# Generated by Django 5.0.4 on 2024-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornone', '0005_person_delete_admin_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
