# Generated by Django 5.0.4 on 2024-05-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornone', '0006_person_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(max_length=20)),
                ('paragraph', models.TextField(max_length=500, verbose_name='description')),
            ],
        ),
    ]
