# Generated by Django 5.0.4 on 2024-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornone', '0007_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isAdmin',
            field=models.BooleanField(default=True),
        ),
    ]
