# Generated by Django 5.0.4 on 2024-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornone', '0008_alter_person_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
